[profile.default]
solc = "0.8.27"
src = "src"
out = "out"
libs = ["dependencies"]
remappings = ["forge-std/=dependencies/forge-std-1.9.4/src/"]

[dependencies]
forge-std = { version = "1.9.4" }

[soldeer]
remappings_generate = false
remappings_regenerate = false

[fuzz]
runs = 256

[invariant]
runs = 128
depth = 128
fail_on_revert = false

[fmt]
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
